### ISSUE TITLE
Celos-CI alpha release checklist

### ISSUE THREAD

**Issue by manuel** [collectivemedia/celos#251]
- [ ] Sample MapReduce wordcount workflow
  - [x] Uses `celos-ci.jar` from Nexus repo
  - [x] Can be tested on developer machine
  - [ ] Automatically run from celos-ci's test suite
  - [x] Standard directory structure: `src/main/{celos,oozie,java}`
  - [ ] Multiple test cases under `src/test/celos-ci/test-N`
  - [ ] Sabotage test cases that show that failures are detected and reported (like `file-copy-with-bad-output`, ... in Celos integration tests)
  - [x] Basic HOWTO documentation
- [x] Celos-CI PR merged
  - [x] Code cleanups
  - [x] `celos-ci.jar` deployed to Nexus from Jenkins
- [x] Targets
  - [x] Testing target `celos001:/etc/celos/targets/testing.json`

Blocked
- [ ] Blocked because CI can't talk to NY7: Automatically tested on CI box https://jira.collective.com/browse/INFPROJ-66 

Post Alpha stuff
- [ ] Combine TestRun and TestContext?
- [ ] Different Context classes for test/deploy/undeploy?
